'use client';
import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, ExternalLink, Minus, TrendingDown, TrendingUp } from 'lucide-react';
import type { ResultItem } from '@/lib/types';

export const DataGrid = ({ results }: { results: ResultItem[] }) => {
  const [page, setPage] = useState(1); const pageSize = 5; const totalPages = Math.ceil(results.length / pageSize); const displayed = results.slice((page - 1) * pageSize, page * pageSize);
  if (!results.length) return <div className="panel p-10 text-center text-sm text-[#74766f]">No sources found for this analysis.</div>;
  const badge = (s: string) => { const lower = s.toLowerCase(); const positive = lower === 'positive'; const negative = lower === 'negative'; const Icon = positive ? TrendingUp : negative ? TrendingDown : Minus; return <span className="inline-flex items-center gap-1.5 text-xs font-semibold"><Icon className="h-3.5 w-3.5" />{s}</span>; };
  return <section className="panel overflow-hidden"><div className="flex items-end justify-between border-b border-[#d9d5cb] px-5 py-5"><div><p className="eyebrow">Evidence</p><h3 className="mt-1 font-serif text-2xl">Source review</h3></div><span className="text-xs text-[#74766f]">{results.length} sources</span></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="border-b border-[#e1ddd4] text-[10px] uppercase tracking-[0.14em] text-[#8b887f]"><tr><th className="px-5 py-3">Source</th><th className="px-5 py-3">Snippet</th><th className="px-5 py-3">Signal</th><th className="px-5 py-3 text-right">Hits</th></tr></thead><tbody>{displayed.map((item) => <tr key={item.id} className="border-b border-[#ece8e0] align-top last:border-0 hover:bg-[#faf8f3]"><td className="max-w-[270px] px-5 py-4"><div className="truncate text-sm font-semibold">{item.title}</div><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-1 truncate text-xs text-[#74766f] hover:text-[#20221d]"><span className="truncate">{item.sourceUrl}</span><ExternalLink className="h-3 w-3 shrink-0" /></a></td><td className="max-w-[430px] px-5 py-4 text-sm leading-6 text-[#74766f]">{item.snippet}</td><td className="px-5 py-4">{badge(item.sentiment)}</td><td className="px-5 py-4 text-right font-mono text-sm">{item.mentions}</td></tr>)}</tbody></table></div>{totalPages > 1 && <div className="flex items-center justify-between border-t border-[#d9d5cb] px-5 py-3 text-xs text-[#74766f]"><span>{(page - 1) * pageSize + 1}–{Math.min(page * pageSize, results.length)} of {results.length}</span><div className="flex items-center gap-2"><button className="quiet-button !p-1.5 disabled:opacity-30" disabled={page === 1} onClick={() => setPage((p) => p - 1)}><ChevronLeft className="h-4 w-4" /></button><span>{page} / {totalPages}</span><button className="quiet-button !p-1.5 disabled:opacity-30" disabled={page === totalPages} onClick={() => setPage((p) => p + 1)}><ChevronRight className="h-4 w-4" /></button></div></div>}</section>;
};
